using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL{
    /// <summary>
    /// Strongly-typed collection for the ActiveProject class.
    /// </summary>
    [Serializable]
    public partial class ActiveProjectCollection : ReadOnlyList<ActiveProject, ActiveProjectCollection>
    {        
        public ActiveProjectCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the ActiveProjects view.
    /// </summary>
    [Serializable]
    public partial class ActiveProject : ReadOnlyRecord<ActiveProject>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("ActiveProjects", TableType.View, DataService.GetInstance("VeritasInfo"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"dbo";
                //columns
                
                TableSchema.TableColumn colvarProject = new TableSchema.TableColumn(schema);
                colvarProject.ColumnName = "Project";
                colvarProject.DataType = DbType.AnsiString;
                colvarProject.MaxLength = 203;
                colvarProject.AutoIncrement = false;
                colvarProject.IsNullable = false;
                colvarProject.IsPrimaryKey = false;
                colvarProject.IsForeignKey = false;
                colvarProject.IsReadOnly = false;
                
                schema.Columns.Add(colvarProject);
                
                TableSchema.TableColumn colvarAssignedPM = new TableSchema.TableColumn(schema);
                colvarAssignedPM.ColumnName = "AssignedPM";
                colvarAssignedPM.DataType = DbType.AnsiString;
                colvarAssignedPM.MaxLength = 50;
                colvarAssignedPM.AutoIncrement = false;
                colvarAssignedPM.IsNullable = false;
                colvarAssignedPM.IsPrimaryKey = false;
                colvarAssignedPM.IsForeignKey = false;
                colvarAssignedPM.IsReadOnly = false;
                
                schema.Columns.Add(colvarAssignedPM);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["VeritasInfo"].AddSchema("ActiveProjects",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public ActiveProject()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public ActiveProject(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public ActiveProject(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public ActiveProject(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Project")]
        [Bindable(true)]
        public string Project 
	    {
		    get
		    {
			    return GetColumnValue<string>("Project");
		    }
            set 
		    {
			    SetColumnValue("Project", value);
            }
        }
	      
        [XmlAttribute("AssignedPM")]
        [Bindable(true)]
        public string AssignedPM 
	    {
		    get
		    {
			    return GetColumnValue<string>("AssignedPM");
		    }
            set 
		    {
			    SetColumnValue("AssignedPM", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Project = @"Project";
            
            public static string AssignedPM = @"AssignedPM";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
