using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for A_CallLog
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CallLogController
    {
        // Preload our schema..
        CallLog thisSchemaLoad = new CallLog();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CallLogCollection FetchAll()
        {
            CallLogCollection coll = new CallLogCollection();
            Query qry = new Query(CallLog.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CallLogCollection FetchByID(object Id)
        {
            CallLogCollection coll = new CallLogCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CallLogCollection FetchByQuery(Query qry)
        {
            CallLogCollection coll = new CallLogCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (CallLog.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (CallLog.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(DateTime? CallReceived,string CallerName,string CallerCompany,string CallerNumber,string Notes,int? ProjectID,string VeritasEmployee,string EnteredBy,DateTime? EnteredDate)
	    {
		    CallLog item = new CallLog();
		    
            item.CallReceived = CallReceived;
            
            item.CallerName = CallerName;
            
            item.CallerCompany = CallerCompany;
            
            item.CallerNumber = CallerNumber;
            
            item.Notes = Notes;
            
            item.ProjectID = ProjectID;
            
            item.VeritasEmployee = VeritasEmployee;
            
            item.EnteredBy = EnteredBy;
            
            item.EnteredDate = EnteredDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,DateTime? CallReceived,string CallerName,string CallerCompany,string CallerNumber,string Notes,int? ProjectID,string VeritasEmployee,string EnteredBy,DateTime? EnteredDate)
	    {
		    CallLog item = new CallLog();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CallReceived = CallReceived;
				
			item.CallerName = CallerName;
				
			item.CallerCompany = CallerCompany;
				
			item.CallerNumber = CallerNumber;
				
			item.Notes = Notes;
				
			item.ProjectID = ProjectID;
				
			item.VeritasEmployee = VeritasEmployee;
				
			item.EnteredBy = EnteredBy;
				
			item.EnteredDate = EnteredDate;
				
	        item.Save(UserName);
	    }
    }
}
