using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
	/// <summary>
	/// Strongly-typed collection for the Carrier class.
	/// </summary>
    [Serializable]
	public partial class CarrierCollection : ActiveList<Carrier, CarrierCollection>
	{	   
		public CarrierCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>CarrierCollection</returns>
		public CarrierCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Carrier o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the S_Carriers table.
	/// </summary>
	[Serializable]
	public partial class Carrier : ActiveRecord<Carrier>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Carrier()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Carrier(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Carrier(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Carrier(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("S_Carriers", TableType.Table, DataService.GetInstance("VeritasInfo"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "ID";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarCarrierName = new TableSchema.TableColumn(schema);
				colvarCarrierName.ColumnName = "CarrierName";
				colvarCarrierName.DataType = DbType.AnsiString;
				colvarCarrierName.MaxLength = 30;
				colvarCarrierName.AutoIncrement = false;
				colvarCarrierName.IsNullable = true;
				colvarCarrierName.IsPrimaryKey = false;
				colvarCarrierName.IsForeignKey = false;
				colvarCarrierName.IsReadOnly = false;
				colvarCarrierName.DefaultSetting = @"";
				colvarCarrierName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCarrierName);
				
				TableSchema.TableColumn colvarContactPhone = new TableSchema.TableColumn(schema);
				colvarContactPhone.ColumnName = "ContactPhone";
				colvarContactPhone.DataType = DbType.AnsiString;
				colvarContactPhone.MaxLength = 15;
				colvarContactPhone.AutoIncrement = false;
				colvarContactPhone.IsNullable = true;
				colvarContactPhone.IsPrimaryKey = false;
				colvarContactPhone.IsForeignKey = false;
				colvarContactPhone.IsReadOnly = false;
				colvarContactPhone.DefaultSetting = @"";
				colvarContactPhone.ForeignKeyTableName = "";
				schema.Columns.Add(colvarContactPhone);
				
				TableSchema.TableColumn colvarContactName = new TableSchema.TableColumn(schema);
				colvarContactName.ColumnName = "ContactName";
				colvarContactName.DataType = DbType.AnsiString;
				colvarContactName.MaxLength = 50;
				colvarContactName.AutoIncrement = false;
				colvarContactName.IsNullable = true;
				colvarContactName.IsPrimaryKey = false;
				colvarContactName.IsForeignKey = false;
				colvarContactName.IsReadOnly = false;
				colvarContactName.DefaultSetting = @"";
				colvarContactName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarContactName);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["VeritasInfo"].AddSchema("S_Carriers",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("CarrierName")]
		[Bindable(true)]
		public string CarrierName 
		{
			get { return GetColumnValue<string>(Columns.CarrierName); }
			set { SetColumnValue(Columns.CarrierName, value); }
		}
		  
		[XmlAttribute("ContactPhone")]
		[Bindable(true)]
		public string ContactPhone 
		{
			get { return GetColumnValue<string>(Columns.ContactPhone); }
			set { SetColumnValue(Columns.ContactPhone, value); }
		}
		  
		[XmlAttribute("ContactName")]
		[Bindable(true)]
		public string ContactName 
		{
			get { return GetColumnValue<string>(Columns.ContactName); }
			set { SetColumnValue(Columns.ContactName, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varCarrierName,string varContactPhone,string varContactName)
		{
			Carrier item = new Carrier();
			
			item.CarrierName = varCarrierName;
			
			item.ContactPhone = varContactPhone;
			
			item.ContactName = varContactName;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varCarrierName,string varContactPhone,string varContactName)
		{
			Carrier item = new Carrier();
			
				item.Id = varId;
			
				item.CarrierName = varCarrierName;
			
				item.ContactPhone = varContactPhone;
			
				item.ContactName = varContactName;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn CarrierNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ContactPhoneColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ContactNameColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string CarrierName = @"CarrierName";
			 public static string ContactPhone = @"ContactPhone";
			 public static string ContactName = @"ContactName";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
