using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for InteriorsCategories
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InteriorsCategoryController
    {
        // Preload our schema..
        InteriorsCategory thisSchemaLoad = new InteriorsCategory();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InteriorsCategoryCollection FetchAll()
        {
            InteriorsCategoryCollection coll = new InteriorsCategoryCollection();
            Query qry = new Query(InteriorsCategory.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InteriorsCategoryCollection FetchByID(object Id)
        {
            InteriorsCategoryCollection coll = new InteriorsCategoryCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InteriorsCategoryCollection FetchByQuery(Query qry)
        {
            InteriorsCategoryCollection coll = new InteriorsCategoryCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (InteriorsCategory.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (InteriorsCategory.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string CategoryName,string Description,string SpecSection,int? SpecLevel)
	    {
		    InteriorsCategory item = new InteriorsCategory();
		    
            item.CategoryName = CategoryName;
            
            item.Description = Description;
            
            item.SpecSection = SpecSection;
            
            item.SpecLevel = SpecLevel;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string CategoryName,string Description,string SpecSection,int? SpecLevel)
	    {
		    InteriorsCategory item = new InteriorsCategory();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CategoryName = CategoryName;
				
			item.Description = Description;
				
			item.SpecSection = SpecSection;
				
			item.SpecLevel = SpecLevel;
				
	        item.Save(UserName);
	    }
    }
}
