using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for InteriorsPackageLevels
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InteriorsPackageLevelController
    {
        // Preload our schema..
        InteriorsPackageLevel thisSchemaLoad = new InteriorsPackageLevel();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InteriorsPackageLevelCollection FetchAll()
        {
            InteriorsPackageLevelCollection coll = new InteriorsPackageLevelCollection();
            Query qry = new Query(InteriorsPackageLevel.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InteriorsPackageLevelCollection FetchByID(object Id)
        {
            InteriorsPackageLevelCollection coll = new InteriorsPackageLevelCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InteriorsPackageLevelCollection FetchByQuery(Query qry)
        {
            InteriorsPackageLevelCollection coll = new InteriorsPackageLevelCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (InteriorsPackageLevel.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (InteriorsPackageLevel.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int PackageID,string TrimLevel)
	    {
		    InteriorsPackageLevel item = new InteriorsPackageLevel();
		    
            item.PackageID = PackageID;
            
            item.TrimLevel = TrimLevel;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int PackageID,string TrimLevel)
	    {
		    InteriorsPackageLevel item = new InteriorsPackageLevel();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.PackageID = PackageID;
				
			item.TrimLevel = TrimLevel;
				
	        item.Save(UserName);
	    }
    }
}
