using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for InteriorsSuppliers
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InteriorsSupplierController
    {
        // Preload our schema..
        InteriorsSupplier thisSchemaLoad = new InteriorsSupplier();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InteriorsSupplierCollection FetchAll()
        {
            InteriorsSupplierCollection coll = new InteriorsSupplierCollection();
            Query qry = new Query(InteriorsSupplier.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InteriorsSupplierCollection FetchByID(object Id)
        {
            InteriorsSupplierCollection coll = new InteriorsSupplierCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InteriorsSupplierCollection FetchByQuery(Query qry)
        {
            InteriorsSupplierCollection coll = new InteriorsSupplierCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (InteriorsSupplier.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (InteriorsSupplier.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Company,string MainPhone,string Contact,string ContactPhone,string Fax)
	    {
		    InteriorsSupplier item = new InteriorsSupplier();
		    
            item.Company = Company;
            
            item.MainPhone = MainPhone;
            
            item.Contact = Contact;
            
            item.ContactPhone = ContactPhone;
            
            item.Fax = Fax;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Company,string MainPhone,string Contact,string ContactPhone,string Fax)
	    {
		    InteriorsSupplier item = new InteriorsSupplier();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Company = Company;
				
			item.MainPhone = MainPhone;
				
			item.Contact = Contact;
				
			item.ContactPhone = ContactPhone;
				
			item.Fax = Fax;
				
	        item.Save(UserName);
	    }
    }
}
