using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
	/// <summary>
	/// Strongly-typed collection for the InteriorsPackageLevel class.
	/// </summary>
    [Serializable]
	public partial class InteriorsPackageLevelCollection : ActiveList<InteriorsPackageLevel, InteriorsPackageLevelCollection>
	{	   
		public InteriorsPackageLevelCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>InteriorsPackageLevelCollection</returns>
		public InteriorsPackageLevelCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                InteriorsPackageLevel o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the InteriorsPackageLevels table.
	/// </summary>
	[Serializable]
	public partial class InteriorsPackageLevel : ActiveRecord<InteriorsPackageLevel>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public InteriorsPackageLevel()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public InteriorsPackageLevel(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public InteriorsPackageLevel(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public InteriorsPackageLevel(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("InteriorsPackageLevels", TableType.Table, DataService.GetInstance("VeritasInfo"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "ID";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarPackageID = new TableSchema.TableColumn(schema);
				colvarPackageID.ColumnName = "PackageID";
				colvarPackageID.DataType = DbType.Int32;
				colvarPackageID.MaxLength = 0;
				colvarPackageID.AutoIncrement = false;
				colvarPackageID.IsNullable = false;
				colvarPackageID.IsPrimaryKey = false;
				colvarPackageID.IsForeignKey = false;
				colvarPackageID.IsReadOnly = false;
				colvarPackageID.DefaultSetting = @"";
				colvarPackageID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPackageID);
				
				TableSchema.TableColumn colvarTrimLevel = new TableSchema.TableColumn(schema);
				colvarTrimLevel.ColumnName = "TrimLevel";
				colvarTrimLevel.DataType = DbType.AnsiString;
				colvarTrimLevel.MaxLength = 50;
				colvarTrimLevel.AutoIncrement = false;
				colvarTrimLevel.IsNullable = true;
				colvarTrimLevel.IsPrimaryKey = false;
				colvarTrimLevel.IsForeignKey = false;
				colvarTrimLevel.IsReadOnly = false;
				colvarTrimLevel.DefaultSetting = @"";
				colvarTrimLevel.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrimLevel);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["VeritasInfo"].AddSchema("InteriorsPackageLevels",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("PackageID")]
		[Bindable(true)]
		public int PackageID 
		{
			get { return GetColumnValue<int>(Columns.PackageID); }
			set { SetColumnValue(Columns.PackageID, value); }
		}
		  
		[XmlAttribute("TrimLevel")]
		[Bindable(true)]
		public string TrimLevel 
		{
			get { return GetColumnValue<string>(Columns.TrimLevel); }
			set { SetColumnValue(Columns.TrimLevel, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varPackageID,string varTrimLevel)
		{
			InteriorsPackageLevel item = new InteriorsPackageLevel();
			
			item.PackageID = varPackageID;
			
			item.TrimLevel = varTrimLevel;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int varPackageID,string varTrimLevel)
		{
			InteriorsPackageLevel item = new InteriorsPackageLevel();
			
				item.Id = varId;
			
				item.PackageID = varPackageID;
			
				item.TrimLevel = varTrimLevel;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PackageIDColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn TrimLevelColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string PackageID = @"PackageID";
			 public static string TrimLevel = @"TrimLevel";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
