using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
	/// <summary>
	/// Strongly-typed collection for the LitPackage class.
	/// </summary>
    [Serializable]
	public partial class LitPackageCollection : ActiveList<LitPackage, LitPackageCollection>
	{	   
		public LitPackageCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>LitPackageCollection</returns>
		public LitPackageCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                LitPackage o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the mkt_LitPackages table.
	/// </summary>
	[Serializable]
	public partial class LitPackage : ActiveRecord<LitPackage>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public LitPackage()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public LitPackage(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public LitPackage(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public LitPackage(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("mkt_LitPackages", TableType.Table, DataService.GetInstance("VeritasInfo"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "ID";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarPackageName = new TableSchema.TableColumn(schema);
				colvarPackageName.ColumnName = "PackageName";
				colvarPackageName.DataType = DbType.AnsiString;
				colvarPackageName.MaxLength = 50;
				colvarPackageName.AutoIncrement = false;
				colvarPackageName.IsNullable = false;
				colvarPackageName.IsPrimaryKey = false;
				colvarPackageName.IsForeignKey = false;
				colvarPackageName.IsReadOnly = false;
				colvarPackageName.DefaultSetting = @"";
				colvarPackageName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPackageName);
				
				TableSchema.TableColumn colvarPackageDescription = new TableSchema.TableColumn(schema);
				colvarPackageDescription.ColumnName = "PackageDescription";
				colvarPackageDescription.DataType = DbType.AnsiString;
				colvarPackageDescription.MaxLength = -1;
				colvarPackageDescription.AutoIncrement = false;
				colvarPackageDescription.IsNullable = true;
				colvarPackageDescription.IsPrimaryKey = false;
				colvarPackageDescription.IsForeignKey = false;
				colvarPackageDescription.IsReadOnly = false;
				colvarPackageDescription.DefaultSetting = @"";
				colvarPackageDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPackageDescription);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["VeritasInfo"].AddSchema("mkt_LitPackages",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("PackageName")]
		[Bindable(true)]
		public string PackageName 
		{
			get { return GetColumnValue<string>(Columns.PackageName); }
			set { SetColumnValue(Columns.PackageName, value); }
		}
		  
		[XmlAttribute("PackageDescription")]
		[Bindable(true)]
		public string PackageDescription 
		{
			get { return GetColumnValue<string>(Columns.PackageDescription); }
			set { SetColumnValue(Columns.PackageDescription, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varPackageName,string varPackageDescription)
		{
			LitPackage item = new LitPackage();
			
			item.PackageName = varPackageName;
			
			item.PackageDescription = varPackageDescription;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varPackageName,string varPackageDescription)
		{
			LitPackage item = new LitPackage();
			
				item.Id = varId;
			
				item.PackageName = varPackageName;
			
				item.PackageDescription = varPackageDescription;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PackageNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn PackageDescriptionColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string PackageName = @"PackageName";
			 public static string PackageDescription = @"PackageDescription";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
