using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for A_RoomSurveyPoints
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class RoomSurveyPointController
    {
        // Preload our schema..
        RoomSurveyPoint thisSchemaLoad = new RoomSurveyPoint();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public RoomSurveyPointCollection FetchAll()
        {
            RoomSurveyPointCollection coll = new RoomSurveyPointCollection();
            Query qry = new Query(RoomSurveyPoint.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public RoomSurveyPointCollection FetchByID(object Id)
        {
            RoomSurveyPointCollection coll = new RoomSurveyPointCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public RoomSurveyPointCollection FetchByQuery(Query qry)
        {
            RoomSurveyPointCollection coll = new RoomSurveyPointCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (RoomSurveyPoint.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (RoomSurveyPoint.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? RoomID,string SurveyPoint,string SurveyPointDesc,decimal? OccupancyFactor,decimal? UseFactor,decimal? PELValue,string PELType,decimal? DistanceFromISOFeet,string ExistingShielding,string AdjacentBuildings,decimal? DistanceFromISOMeters)
	    {
		    RoomSurveyPoint item = new RoomSurveyPoint();
		    
            item.RoomID = RoomID;
            
            item.SurveyPoint = SurveyPoint;
            
            item.SurveyPointDesc = SurveyPointDesc;
            
            item.OccupancyFactor = OccupancyFactor;
            
            item.UseFactor = UseFactor;
            
            item.PELValue = PELValue;
            
            item.PELType = PELType;
            
            item.DistanceFromISOFeet = DistanceFromISOFeet;
            
            item.ExistingShielding = ExistingShielding;
            
            item.AdjacentBuildings = AdjacentBuildings;
            
            item.DistanceFromISOMeters = DistanceFromISOMeters;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? RoomID,string SurveyPoint,string SurveyPointDesc,decimal? OccupancyFactor,decimal? UseFactor,decimal? PELValue,string PELType,decimal? DistanceFromISOFeet,string ExistingShielding,string AdjacentBuildings,decimal? DistanceFromISOMeters)
	    {
		    RoomSurveyPoint item = new RoomSurveyPoint();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.RoomID = RoomID;
				
			item.SurveyPoint = SurveyPoint;
				
			item.SurveyPointDesc = SurveyPointDesc;
				
			item.OccupancyFactor = OccupancyFactor;
				
			item.UseFactor = UseFactor;
				
			item.PELValue = PELValue;
				
			item.PELType = PELType;
				
			item.DistanceFromISOFeet = DistanceFromISOFeet;
				
			item.ExistingShielding = ExistingShielding;
				
			item.AdjacentBuildings = AdjacentBuildings;
				
			item.DistanceFromISOMeters = DistanceFromISOMeters;
				
	        item.Save(UserName);
	    }
    }
}
